spring.application.name=backendKasaSklepowa

# Konfiguracja bazy H2 (zapisuje dane w pami?ci - znikn? po restarcie)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Konsola H2 dost?pna pod /h2-console
spring.h2.console.enabled=true

# Hibernate: automatyczne tworzenie tabel
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true