spring.application.name=backendKasaSklepowa
server.port=8080

spring.datasource.url=jdbc:mariadb://db:3306/sklep
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Hibernate: automatyczne tworzenie tabel
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

blik.url=http://blik-backend:8082/api/blik
bank.url=http://blue-bank:8081/api/bank