spring.application.name=backendKasaSklepowa

spring.datasource.url=jdbc:mariadb://localhost:3306/sklep
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Hibernate: automatyczne tworzenie tabel
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

blik.url=http://127.0.0.1:8082/api/blik
bank.url=http://127.0.0.1:8081/api/bank

# --- TRUSTPAY ---
trustpay.api.url=https://trustpay-backend-1orv.onrender.com/api/v1/payments/submit-code
trustpay.webhook.secret=cac8190e42f7a32f00110af02fba56a351317efa7070807ec707f576d2a8bbab
# Gdy testujesz lokalnie, u?yj np. ngrok. Gdy wrzucisz na serwer, podaj prawdziw? domen?:
trustpay.webhook.public-url=https://silk-chaste-deprive.ngrok-free.dev